#Generated by ChatGPT, with modofications
import numpy as np
import pandas as pd

def generate_curve(
        n_points=5000,
        t_min=2460998,
        t_max=2460998 + 50.0,
        noise_sigma=0.2,
        outfile="test_curve.txt"):

    np.random.seed(42)  # for reproducibility

    # Time array
    time = np.linspace(t_min, t_max, n_points)

    periods    = [4.06 , 9.53 , 7.45, 2.22, 6.41]
    amplitudes = [1.1  , 0.35 , 0.66, 0.44, 0.34]
    phases     = [0.365, 5.442, 3.78, 1.56, 3.13]
    a = -0.0016    
    b = 0.0023
    c = 13.3

    # Build the signal
    time0 = time - t_min
    value = (
        a * time0 ** 2 + b * time0 + c +
        amplitudes[0] * np.sin(2*np.pi * time0 / periods[0] + phases[0]) +
        amplitudes[1] * np.sin(2*np.pi * time0 / periods[1] + phases[1]) +
        amplitudes[2] * np.sin(2*np.pi * time0 / periods[2] + phases[2]) +
        amplitudes[3] * np.sin(2*np.pi * time0 / periods[3] + phases[3]) +
        amplitudes[4] * np.sin(2*np.pi * time0 / periods[4] + phases[4]) +
        np.random.normal(0, noise_sigma, n_points)
    )

    # Save
    df = pd.DataFrame({"time": time, "value": value})
    df.to_csv(outfile, sep="\t", index=False, header=False)

    print("File saved as:", outfile)
    print("Periods used:", periods)
    print("Amplitudes used:", amplitudes)
    print("Phases used:", phases)


if __name__ == "__main__":
    generate_curve()
