# This code was generated by ChatGPT!
import tkinter as tk
from tkinter import messagebox
#from tkinter import scrolledtext

class LogWindow(tk.Toplevel):
    def __init__(self, master=None, title="Log Window", geometry=None):
        super().__init__(master)
        self.protocol("WM_DELETE_WINDOW", self.on_close)
        self.title(title)
        if geometry:
            #print(f"geometry: {geometry}")
            self.geometry(geometry)
        else:
            #print("not geometry")
            self.geometry("600x300+100+100")

        # Text widget with scrollbars
        frame = tk.Frame(self)
        frame.pack(fill=tk.BOTH, expand=True)

        xscroll = tk.Scrollbar(frame, orient=tk.HORIZONTAL)
        yscroll = tk.Scrollbar(frame, orient=tk.VERTICAL)
        self.textbox = tk.Text(
            frame, wrap=tk.NONE,
            xscrollcommand=xscroll.set,
            yscrollcommand=yscroll.set
        )
        xscroll.config(command=self.textbox.xview)
        yscroll.config(command=self.textbox.yview)

        # Layout
        self.textbox.grid(row=0, column=0, sticky="nsew")
        yscroll.grid(row=0, column=1, sticky="ns")
        xscroll.grid(row=1, column=0, sticky="ew")

        frame.rowconfigure(0, weight=1)
        frame.columnconfigure(0, weight=1)

    def on_close(self):
        # Do nothing (completely disable closing)
        # or just hide instead of destroying
        pass

    def add_line(self, text):
        """Append a new line to the log."""
        try:
            self.textbox.insert(tk.END, text + "\n")
            self.textbox.see(tk.END)  # Auto-scroll to bottom
        except Exception as e:
            messagebox.showinfo(None, "Error: " + str(e))

    def clear(self):
        """Clear the log text box."""
        try:
            self.textbox.delete(1.0, tk.END)
        except Exception as e:
            messagebox.showinfo(None, "Error: " + str(e))
